services:
  - type: worker
    name: bybit-shortbot-paper
    runtime: python
    plan: starter

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false

    disk:
      name: botdata
      mountPath: /opt/render/project/src
      sizeGB: 1
